version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile

    entrypoint: npm start
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - 3000:3000
    container_name: app
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=thiago
      - MYSQL_ROOT_PASSWORD=qweqwep
    volumes:
      - ./mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
